# Generated by Django 2.1.7 on 2019-03-26 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='meeting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('theme', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True, default='备注为空', max_length=1000, null=True)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('edittime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '会议',
                'verbose_name_plural': '会议',
                'ordering': ['starttime'],
            },
        ),
        migrations.CreateModel(
            name='meeting_user_rel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False)),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.meeting')),
            ],
            options={
                'verbose_name': '签到信息',
                'verbose_name_plural': '签到信息',
            },
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('type', models.CharField(max_length=200)),
                ('comment', models.TextField(blank=True, default='备注为空', max_length=500, null=True)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('edittime', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '会议室',
                'verbose_name_plural': '会议室',
            },
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('sex', models.IntegerField(choices=[(0, '男'), (1, '女')], default=0)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(max_length=50)),
                ('addtime', models.DateTimeField(auto_now_add=True)),
                ('edittime', models.DateTimeField(auto_now=True)),
                ('passwd', models.CharField(default='123456', max_length=200)),
                ('pic', models.ImageField(default='null', upload_to='static/facelib')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
            },
        ),
        migrations.AddField(
            model_name='room',
            name='manager',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.SET_DEFAULT, to='management.user'),
        ),
        migrations.AddField(
            model_name='meeting_user_rel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.user'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='creat_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='creat_person', to='management.user', verbose_name='管理员'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='person',
            field=models.ManyToManyField(related_name='person', through='management.meeting_user_rel', to='management.user', verbose_name='会议人员'),
        ),
        migrations.AddField(
            model_name='meeting',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.room'),
        ),
        migrations.AlterUniqueTogether(
            name='meeting_user_rel',
            unique_together={('user', 'meeting')},
        ),
    ]
