# Generated by Django 2.1.7 on 2019-03-22 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190322_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meeting',
            name='theme',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='room',
            name='type',
            field=models.CharField(max_length=200),
        ),
    ]
