# Generated by Django 2.1.7 on 2019-03-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20190322_1536'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='meeting_user_rel',
            options={'verbose_name': '签到信息', 'verbose_name_plural': '签到信息'},
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
