# Generated by Django 2.1.7 on 2019-03-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20190323_2337'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='passwd',
            field=models.CharField(default='123456', max_length=200),
        ),
    ]
