# Generated by Django 2.1.7 on 2019-03-26 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0006_user_passwd'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pic',
            field=models.ImageField(default='null', upload_to='booktest/'),
        ),
    ]
