# Generated by Django 2.1.7 on 2019-03-26 22:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20190326_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='manager',
            field=models.ForeignKey(default='null', on_delete=django.db.models.deletion.SET_DEFAULT, to='management.user'),
        ),
    ]
